name: Hello World

on: 
    workflow_dispatch:

    # schedule:
    #     - cron: "* * * * *"
    # push

jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
            - name: Echo text
              run: echo "Hello, world!"
